-- leads table
CREATE TABLE `leads` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` smallint(5) unsigned NOT NULL,
  `organisation_id` int(10) unsigned DEFAULT NULL,
  `team_id` int(10) unsigned DEFAULT NULL,
  `activity` varchar(70) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `status` varchar(60) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `gender` enum('male','female') COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `firstname` varchar(120) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `lastname` varchar(120) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `postcode` varchar(6) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `housenumber` varchar(5) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `suffix` varchar(6) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `streetname` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `city` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `country` varchar(2) COLLATE utf8mb3_unicode_ci DEFAULT 'NL',
  `birthdate` date DEFAULT NULL,
  `email` varchar(120) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `phone` varchar(15) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `business` enum('0','1') COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '0',
  `company_name` varchar(120) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `contact_person` varchar(120) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `data` text COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `attachments` text COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `history` text COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_ip` varchar(45) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `planned_user_id` int(10) unsigned DEFAULT NULL,
  `planned_date` date DEFAULT NULL,
  `planned_by` int(10) unsigned DEFAULT NULL,
  `planned_at` timestamp NULL DEFAULT NULL,
  `planned_from` timestamp NULL DEFAULT NULL,
  `planned_to` timestamp NULL DEFAULT NULL,
  `planned_duration` smallint(6) DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `completed_team_id` int(10) unsigned DEFAULT NULL,
  `completed_by` int(10) unsigned DEFAULT NULL,
  `started_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_account_deleted_id` (`account_id`, `deleted_at`, `id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
